### ISSUE TITLE
Pointers misbehave on undo

### ISSUE THREAD

**Issue by X455u** [vkaravir/JSAV#181]
The pointer arrow will not return to its previous location when the user clicks _undo_ in an **exercise**.

Example: [OpenDSA/AV/Development/interpolationSearchPRO2.html](https://github.com/OpenDSA/OpenDSA/blob/master/AV/Development/interpolationSearchPRO2.html)

The problem seems to be fixed by wrapping `pointerproto._translateArrowPoints` inside a `JSAV.anim` wrapper, but I'm not sure if that's a good idea.

**Comment by vkaravir** [comment]
Should be ok to wrap it inside JSAV.anim. You should then probably add {record:false} as the last param to the movePoints call to prevent it from recording a new animation step every time the aniamted step is executed.

**Comment by X455u** [comment]
There seems to be something strange going on with _setattrs() in [graphicals:js:62](https://github.com/vkaravir/JSAV/blob/master/src/graphicals.js#L62). It's called four times for each pointer when I click undo. 

... I did some research... Seems like the step() call in the undo function ([exercise.js:413](https://github.com/vkaravir/JSAV/blob/master/src/exercise.js#L413)) triggers "jsav-updaterelative", which again triggers [_arrowUpdateRelativeListener](https://github.com/vkaravir/JSAV/blob/master/src/code.js#L204) which calls [_translateArrowPoints](https://github.com/vkaravir/JSAV/blob/master/src/code.js#L218) which calls [movePoints](https://github.com/vkaravir/JSAV/blob/master/src/graphicals.js#L199) and draws the arrow at the old position. (This also creates a new animatable step)

However, when I tried to fix this the list pointers broke...

**Comment by X455u** [comment]
Apparently it was one of my console.logs that broke the list pointers...

**Comment by vkaravir** [comment]
Thank you for the fix!
