### ISSUE TITLE
Graph edges not using correct endpoint when node label has MathJax equation

### ISSUE THREAD

**Issue by cashaffer** [vkaravir/JSAV#187]
Take a look at, for example, http://algoviz.org/OpenDSA/dev/OpenDSA/Books/NP/html/threeSAT_to_clique.html. You can see starting at slide 6 that the endpoints for the edges are not right. Those edges are trying to connect to nodes that are elongated based on the raw text of the label. Fortunately, the label and the node renders correctly. But the edges are not located correctly.

One possibility is to handle the computation correctly in the sense of using the post-mathjax positioning. If that is too hard, then nother option would be to draw the edges ignoring the node label and simply use the base node size (as a circle). Since there are likely times when the node *will* be elongated due to a long label, perhaps there should be an option switch to turn this computation on and off.

**Comment by vkaravir** [comment]
In a way, JSAV is doing what it's supposed to do. The size of the nodes at the time the graph layout is calculated is based on the elongated math label. Then, once the math in the label is rendered, JSAV resizes the nodes. And I'm assuming the layout function is not called again after that.

I don't have a good idea on how to fix the mathjax issues. The mathjax rendering is asynchronous, and JSAV expects the AV recording to be done synchronously (without any callback functions or anything). Fixing this (and the other mathjax issues) properly would probably require a major rethinking of how JSAV records the animations.

As a workaround for this case, you could try disabling the automatic resizing of the nodes using the ```autoresize: false``` option. It should force the size of the nodes to be the default size (45px?) and thus for the edge positions to be calculated correctly.

**Comment by cashaffer** [comment]
using the ``autoresize: false`` option effectively implements what I described above. That is sufficient for us now. Thanks!
