### ISSUE TITLE
Index labels too close in horizontal array with bars

### ISSUE THREAD

**Issue by cashaffer** [vkaravir/JSAV#196]
See for example http://algoviz.org/OpenDSA/AV/Sorting/insertionsortAV.html.

The index labels below the bars need to go down a couple pixels. I didn't find how to do this in JSAV.css.

**Comment by vkaravir** [comment]
Changed in the commit 9c21375 above. Are they down enough? If not, feel free to change the values changed by the commit.

**Comment by cashaffer** [comment]
Looks good, thank you!
