### ISSUE TITLE
relativeTo positioning

### ISSUE THREAD

**Issue by fpopineau** [vkaravir/JSAV#197]
I wanted to try to position 2 elements one relatively  to the other, but I failed to do so.
My attempt is :
```javascript
function test () {
    var jsav = new JSAV("container", {"animationMode": 'none'});
    var code = jsav.code(['Ceci','est un','exemple','de','programme'], {relativeTo: jsav, width: 200, left: 30});
    code.show();
    var g = jsav.ds.graph({layout: 'manual', directed: true, relativeTo: jsav, left:300});
    var a = g.addNode('a', {left: 0, top: 100});
    var b = g.addNode('b', {left: 100, top: 0});
    var c = g.addNode('c', {left: 100, top: 200});
    g.addEdge(a, b);
    g.addEdge(a, c);
    g.layout();
}
```
[Edit:] I understand that css allows to position element relatively to their container. So I updated the code above to position relatively to the JSAV object.

I tried the same kind of thing with an array instead of a code element with no success.
Is this relativeTo option meant to work this way ?
Thanks in advance.

**Comment by vkaravir** [comment]
Hi!
The relative positioning is for positioning elements relative to each other, not relative to the jsav container. So, you could position the graph relative to the code element like this:

```var g = jsav.ds.graph({layout: 'manual', directed: true, relativeTo: code, left:300});```

Hope this helps.

**Comment by fpopineau** [comment]
Thanks. It helps.
I also spotted that adding jquery-ui helped :-)

Regards,

2015-08-15 17:03 GMT+02:00 Ville Karavirta <notifications@github.com>:
